name: Release Notes Test

on:
  milestone:
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./release_notes
        id: create_release_notes
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "The output is ${{ steps.create_release_notes.outputs.release_notes }}"
